### ISSUE TITLE
Why does this app access the network?

### ISSUE THREAD

**Issue by mijorus** [alfeugds/adskipper#7]
Hi, 
from the app Info, Android reports a small network activity in the background.

What is it doing?
I inpected the code but couldn't find anything

**Comment by mijorus** [comment]
I ha e a nothing phone
Il mer 5 apr 2023, 15:04 Alfeu Santos ***@***.***> ha scritto:

**Comment by alfeugds** [comment]
Thanks for sending out your device info. I've never tested the app on Android 13. That raises my suspicion that it is something specific to either Android 13 or Nothing phone.

I'd suggest you to use something like https://github.com/M66B/NetGuard to try and see what's being sent out from your phone from AdSkipper specifically, for peace of mind.

Hopefully there's nothing to worry about, just Google logging stuff as usual. What bugs me is the fact that it shows as if the app is doing these requests.
